name: Set Type from Label
on:
  issues:
    types: [labeled]
jobs:
  set-type:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to renancvitor
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          assignees: renancvitor
      - name: Update Project v2 Type
        uses: nipe0324/update-project-v2-item-field@c4af58452d1c5a788c1ea4f20e073fa722ec4a6b # v2.0.2
        if: ${{ contains(fromJson('["feature","bug","refactor","tech-debt","docs","research"]'), github.event.label.name) }}
        with:
          project-url: https://github.com/users/renancvitor/projects/3
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: 'Type'
          field-value: ${{ github.event.label.name == 'feature' && 'Feature' || github.event.label.name == 'bug' && 'Bug' || github.event.label.name == 'refactor' && 'Refactor' || github.event.label.name == 'tech-debt' && 'Tech Debt' || github.event.label.name == 'docs' && 'Documentation' || github.event.label.name == 'research' && 'Research' }}
